name: CI

on: [push, pull_request]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  
jobs:

  update_nightly_release:
    runs-on: ubuntu-latest
    steps:
      - name: Demo File
        run: date >> output.txt
      - name: Update Nightly
        run: gh release upload nightly *.txt -R ${{github.repository}} --clobber
